### ISSUE TITLE
Convert to supported a11y plugin

### ISSUE THREAD

**Issue by pohnemus** [tclindner/eslint-config-vue-tc#134]
The plugin we're currently utilizing has been abandoned in favor of https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility. I suggest we convert to it using the "recommended" ruleset. Let me know if you agree and if so, I'll get working on this.

* https://github.com/maranran/eslint-plugin-vue-a11y/issues/28#issuecomment-633150519

**Comment by tclindner** [comment]
That sounds good to me 🙌
