### ISSUE TITLE
Add support for eslint-plugin-vue v8.x.x

### ISSUE THREAD

**Issue by tclindner** [tclindner/eslint-config-vue-tc#321]
[Release & Migration Guide](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v8.0.0)

**Comment by pohnemus** [comment]
Thoughts on adding this in v9 and just doing eslint 8 with v8?

**Comment by tclindner** [comment]
Sounds good to me! Do you think we should swap them since Airbnb will likely be a while until they add ESLint 8 support?

**Comment by pohnemus** [comment]
Yea good call 👍
