### ISSUE TITLE
Consider adding vue/v-slot-style

### ISSUE THREAD

**Issue by phil-rw** [tclindner/eslint-config-vue-tc#42]
https://github.com/vuejs/eslint-plugin-vue/issues/801

**Comment by tclindner** [comment]
@phil-rw are you thinking about going with the default options? I'm not a huge fan of shorthand, but I can definitely be supportive if we want to go with the default. 
https://eslint.vuejs.org/rules/v-slot-style.html#options

**Comment by phil-rw** [comment]
@tclindner yes, I would go with the default, but don't have strong feelings either way.
